version: '2'

services:
  wechat:
    image: richole/wechat
    container_name: wechat
    network_mode: "bridge"
    build: .
    restart: "always"
    ports:
      - "9000:3000"
    networks:
      - wechat

networks:
  wechat:
    external:
      name: database_database